# Generated by Django 4.2.7 on 2023-12-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
